#	Síntesis {#cap:sint} 

## Principales conclusiones 

  La distribución teórica que minimizo los valores del criterio de información de Akaike (AIC) y del criterio de información bayesiano (BIC), demostrando el mejor ajuste a los datos de concentración PM~2.5~ fue la distribución gamma. 
  
  Las características temporales de la serie de concentración de PM~2.5~ permiten explicar parte de la variabilidad de la misma. A su vez las características espaciales, referidas a la ubicación y la influencia diferencial de la micro escala en cada uno de los usos de suelo, permite explicar la discrepancia en la magnitud de concentraciones de PM~2.5~ existentes.
  
  Las características temporales de la serie promedio de concentración de PM~2.5~ se mantienen constantes independientemente del uso de suelo, reflejando el mismo patrón de variación a lo largo de las distintas escalas temporales. A pesar de mostrar un patrón de variación similar, puede destacarse que el mismo se ve atenuado en cuanto a la magnitud de las concentraciones en la serie agrícola y área verde en comparación con la serie urbana. Este hecho refleja que el patrón de variación de la concentración de PM~2.5~ responde a una dinámica temporal similar, que se encuentra fuertemente influenciada por las condiciones espaciales de los sitios que se estén analizando.  
  
  El análisis exploratorio confirmó la diferencia existente entre las series temporales provenientes de distintos usos de suelo. La serie de datos proveniente de entornos agrícolas y área verde demostró ser una de concentraciones de menor magnitud, mayormente concentradas en función de su media, demostrando menores fluctuaciones entre valores de elevada y baja magnitud, caracterizándose por ser una serie temporal de menor variabilidad en comparación con la urbana. Por su parte, la serie de datos proveniente de entornos urbanos, demostró ser una que toma valores de mayor magnitud, más dispersa respecto de su media, demostrando gran cantidad de fluctuaciones entre valores de baja y elevada magnitud, es decir de mayor variabilidad. 
  
  Finalmente, junto con la variación de las escalas temporales de mayor magnitud, como los meses y estaciones, se identificó la variación de las condiciones meteorológicas a lo largo de los mismos. Esta variación demostró potencial para explicar la variabilidad de la concentración de PM~2.5~, independientemente del uso de suelo que se esté considerando.
  
  Los resultados obtenidos indican que los modelos predictivos desarrollados logran explicar la variabilidad de la concentración de PM~2.5~ a partir de variables satelitales y temporales.
 
  La similitud existente entre las métricas obtenidas para el modelo de referencia  y las de los modelos predictivos desarrollados demuestran que estos poseen potencial para cumplir el objetivo de alertar a la población ante condiciones adversas de calidad de aire con cinco días de anticipación. 
 
  Las características propias de cada una de las series temporales bajo los distintos usos de suelo y las de aprendizaje de cada uno de los algoritmos predictivos evaluados, fueron determinantes en los resultados de mejor ajuste para cada uno de los usos de suelo. 

  La serie de tiempo de concentración de PM~2.5~ en el uso de suelo agrícola y área verde exhibe una menor variabilidad, la cual impacta en la cantidad de información necesaria para explicar sus variaciones. Este hecho es sustentado en que bajo los distintos enfoques de bases de datos las variables: temperatura del punto de roció, estación codificación coseno, integral vertical de temperatura, mes codificación seno, tasa media de escorrentía subterránea y estación codificación seno permanecen siempre contenidas dentro de las diez de mayor importancia relativa. Por otra parte, para la serie de tiempo proveniente de entornos urbanos, al demostrar tener una mayor variabilidad, se necesita mayor cantidad de información para explicar su variación, motivo por el cual los mejores resultados en el modelado predictivo se hallan bajo el enfoque de la base de datos original. 

  Series temporales con características de mayor variabilidad son más aptas para ser modeladas a través de redes neuronales recurrentes. Mientras que series temporales de menor variabilidad son mas aptas para ser modeladas bajo el algoritmo de bosques aleatorios. 
  
## Futuras lineas de investigación
  
  En primera instancia se propone como futuro lineamiento de continuación de esta tesis el estudio de la variabilidad conjunta de la concentración de PM~2.5~  con respecto a las variables satelitales de forma individual, con el objetivo de identificar cuáles son las que más se vinculan a la fluctuación de la concentración de este contaminante. De esta forma se podrá identificar cuales son las variables de mayor relevancia para explicar la variabilidad de la variable respuesta sin la necesidad de implementar métodos de selección de variables que realicen esta tarea. 
  
  En segundo lugar, se promueve hacer hincapié en la comparación del desempeño de los modelos predictivos de concentración de PM~2.5~  con otros algoritmos predictivos que implementen otro tipo de dato, como por ejemplo imágenes satelitales o bien la combinación de datos satelitales y meteorológicos con imágenes.
  
  En tercer lugar se propone implementar un procedimiento de simulación para verificar los resultados obtenidos en la presente tesis. Este tendría por objetivo simular dos series una que demuestre un alto grado de variabilidad y otra con uno bajo, ademas de múltiples variables respuestas. Una vez llevada a cabo la simulación proceder al ajuste de los modelos predictivos mencionados en la presente tesis, para discernir si a través de datos simulados se alcanza las mismas conclusiones. La principal conclusión a refutar es la que refiere a que series temporales con características de gran variabilidad y fluctuaciones entre sus valores son más aptas para ser modeladas a través de redes neuronales recurrentes. Mientras que series temporales de baja variabilidad y fluctuaciones entre sus valores muestran un mejor desempeño bajo el algoritmo de bosques aleatorios. 
  
  Finalmente, se propone la implementación del modelo predictivo en producción, este inciso persigue el objetivo de poner en funcionamiento el modelo desarrollado, permitiendo la consulta de datos por medio de la población, paleando la inaccesibilidad a datos de contaminación atmosférica.